In [1]:
from model import SiameseBiLSTM, as_keras_metric, precision_threshold, recall_threshold
from inputHandler import word_embed_meta_data, create_test_data, create_train_dev_set
from config import siamese_config
from operator import itemgetter
import tensorflow as tf
from keras.models import load_model
import pandas as pd
import matplotlib.pyplot as plt

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Anaconda3\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
df = pd.read_csv('sample_data.csv')

sentences1 = list(df['sentences1'])
sentences2 = list(df['sentences2'])
is_similar = list(df['is_similar'])

del df
sent = []
for sentence in sentences1 + sentences2:
    new_sentence = []
    for word in sentence.split():
        word = word.lower()
        new_sentence.append(word)
    sent.append(new_sentence)
    
# print (sent)    

tokenizer, embedding_matrix = word_embed_meta_data(sent, siamese_config['EMBEDDING_DIM'])

embedding_meta_data = {
    'tokenizer': tokenizer,
    'embedding_matrix': embedding_matrix }

sentences_pair = [(x1, x2) for x1, x2 in zip(sentences1, sentences2)]

class Configuration(object):
    pass

CONFIG = Configuration()
CONFIG.embedding_dim = siamese_config['EMBEDDING_DIM']
CONFIG.max_sequence_length = siamese_config['MAX_SEQUENCE_LENGTH']
CONFIG.number_lstm_units = siamese_config['NUMBER_LSTM']
CONFIG.rate_drop_lstm = siamese_config['RATE_DROP_LSTM']
CONFIG.number_dense_units = siamese_config['NUMBER_DENSE_UNITS']
CONFIG.activation_function = siamese_config['ACTIVATION_FUNCTION']
CONFIG.rate_drop_dense = siamese_config['RATE_DROP_DENSE']
CONFIG.validation_split_ratio = siamese_config['VALIDATION_SPLIT']

siamese = SiameseBiLSTM(CONFIG.embedding_dim , CONFIG.max_sequence_length, CONFIG.number_lstm_units , CONFIG.number_dense_units, 
                 CONFIG.rate_drop_lstm, CONFIG.rate_drop_dense, CONFIG.activation_function, CONFIG.validation_split_ratio)

best_model_path, model, history = siamese.train_model(sentences_pair, is_similar, embedding_meta_data, model_save_directory='./', epochs = 500, threshold = 0.3)


Embedding matrix shape: (3052, 50)
Null word embeddings: 1
Train on 450 samples, validate on 49 samples
Epoch 1/500
450/450 [==============================] - 11s 25ms/step - loss: 0.9081 - acc: 0.5267 - precision: 0.4107 - recall: 0.7643 - val_loss: 0.5680 - val_acc: 0.7143 - val_precision: 0.5122 - val_recall: 1.0000
Epoch 2/500
450/450 [==============================] - 2s 4ms/step - loss: 0.8450 - acc: 0.5644 - precision: 0.4338 - recall: 0.8312 - val_loss: 0.5369 - val_acc: 0.7755 - val_precision: 0.6176 - val_recall: 1.0000
Epoch 3/500
450/450 [==============================] - 2s 4ms/step - loss: 0.8763 - acc: 0.5444 - precision: 0.4387 - recall: 0.7804 - val_loss: 0.5741 - val_acc: 0.6939 - val_precision: 0.6176 - val_recall: 1.0000
Epoch 4/500
450/450 [==============================] - 2s 4ms/step - loss: 0.7638 - acc: 0.5933 - precision: 0.4552 - recall: 0.8174 - val_loss: 0.5293 - val_acc: 0.5918 - val_precision: 0.6333 - val_recall: 0.9048
Epoch 5/500
450/450 [=============

Epoch 76/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5941 - acc: 0.6578 - precision: 0.4910 - recall: 0.7970 - val_loss: 0.5394 - val_acc: 0.6531 - val_precision: 0.6061 - val_recall: 0.9524
Epoch 77/500
450/450 [==============================] - 1s 3ms/step - loss: 0.6112 - acc: 0.6644 - precision: 0.4940 - recall: 0.7511 - val_loss: 0.5467 - val_acc: 0.6735 - val_precision: 0.5676 - val_recall: 1.0000
Epoch 78/500
450/450 [==============================] - 1s 3ms/step - loss: 0.6365 - acc: 0.6267 - precision: 0.4811 - recall: 0.7923 - val_loss: 0.5363 - val_acc: 0.6735 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 79/500
450/450 [==============================] - 1s 3ms/step - loss: 0.6079 - acc: 0.6422 - precision: 0.4819 - recall: 0.7918 - val_loss: 0.5261 - val_acc: 0.7143 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 80/500
450/450 [==============================] - 2s 4ms/step - loss: 0.6090 - acc: 0.6489 - precision: 0.4870 - recall: 0.7983 - 

Epoch 114/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5993 - acc: 0.6444 - precision: 0.4797 - recall: 0.8159 - val_loss: 0.5495 - val_acc: 0.7755 - val_precision: 0.5122 - val_recall: 1.0000
Epoch 115/500
450/450 [==============================] - 1s 3ms/step - loss: 0.6140 - acc: 0.6467 - precision: 0.4629 - recall: 0.7443 - val_loss: 0.5323 - val_acc: 0.7959 - val_precision: 0.5526 - val_recall: 1.0000
Epoch 116/500
450/450 [==============================] - 1s 3ms/step - loss: 0.6291 - acc: 0.6444 - precision: 0.4468 - recall: 0.7902 - val_loss: 0.5437 - val_acc: 0.6735 - val_precision: 0.6000 - val_recall: 1.0000
Epoch 117/500
450/450 [==============================] - 1s 3ms/step - loss: 0.6144 - acc: 0.6311 - precision: 0.4730 - recall: 0.8306 - val_loss: 0.5747 - val_acc: 0.6735 - val_precision: 0.5667 - val_recall: 0.8095
Epoch 118/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5971 - acc: 0.6289 - precision: 0.5039 - recall: 0.88

Epoch 152/500
450/450 [==============================] - 2s 5ms/step - loss: 0.6435 - acc: 0.6156 - precision: 0.4442 - recall: 0.8204 - val_loss: 0.5528 - val_acc: 0.6122 - val_precision: 0.5938 - val_recall: 0.9048
Epoch 153/500
450/450 [==============================] - 2s 5ms/step - loss: 0.6169 - acc: 0.6489 - precision: 0.4592 - recall: 0.8233 - val_loss: 0.5431 - val_acc: 0.6122 - val_precision: 0.6129 - val_recall: 0.9048
Epoch 154/500
450/450 [==============================] - 2s 4ms/step - loss: 0.6061 - acc: 0.6644 - precision: 0.4527 - recall: 0.8221 - val_loss: 0.5260 - val_acc: 0.6327 - val_precision: 0.5882 - val_recall: 0.9524
Epoch 155/500
450/450 [==============================] - 2s 5ms/step - loss: 0.5948 - acc: 0.6533 - precision: 0.4845 - recall: 0.8659 - val_loss: 0.5746 - val_acc: 0.6122 - val_precision: 0.6429 - val_recall: 0.8571
Epoch 156/500
450/450 [==============================] - 2s 4ms/step - loss: 0.6123 - acc: 0.6422 - precision: 0.4702 - recall: 0.84

Epoch 227/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5861 - acc: 0.6333 - precision: 0.4775 - recall: 0.8381 - val_loss: 0.5523 - val_acc: 0.5714 - val_precision: 0.6061 - val_recall: 0.9524
Epoch 228/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5848 - acc: 0.6622 - precision: 0.4752 - recall: 0.8537 - val_loss: 0.5485 - val_acc: 0.5714 - val_precision: 0.6061 - val_recall: 0.9524
Epoch 229/500
450/450 [==============================] - 2s 4ms/step - loss: 0.6010 - acc: 0.6644 - precision: 0.4724 - recall: 0.8702 - val_loss: 0.5392 - val_acc: 0.6735 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 230/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5860 - acc: 0.6600 - precision: 0.4856 - recall: 0.9045 - val_loss: 0.5371 - val_acc: 0.7143 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 231/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5873 - acc: 0.6578 - precision: 0.4745 - recall: 0.89

Epoch 265/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5798 - acc: 0.6244 - precision: 0.4804 - recall: 0.9354 - val_loss: 0.5893 - val_acc: 0.5714 - val_precision: 0.6667 - val_recall: 0.8571
Epoch 266/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5706 - acc: 0.6511 - precision: 0.4929 - recall: 0.9035 - val_loss: 0.5743 - val_acc: 0.5714 - val_precision: 0.6552 - val_recall: 0.9048
Epoch 267/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5841 - acc: 0.6578 - precision: 0.4625 - recall: 0.8874 - val_loss: 0.5602 - val_acc: 0.5714 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 268/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5811 - acc: 0.6511 - precision: 0.4620 - recall: 0.8917 - val_loss: 0.5529 - val_acc: 0.5510 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 269/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5798 - acc: 0.6600 - precision: 0.4646 - recall: 0.87

Epoch 303/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5661 - acc: 0.6689 - precision: 0.4835 - recall: 0.9339 - val_loss: 0.5284 - val_acc: 0.6531 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 304/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5836 - acc: 0.6489 - precision: 0.4775 - recall: 0.9160 - val_loss: 0.5315 - val_acc: 0.7551 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 305/500
450/450 [==============================] - 2s 4ms/step - loss: 0.6007 - acc: 0.6222 - precision: 0.4548 - recall: 0.8744 - val_loss: 0.5296 - val_acc: 0.7551 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 306/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5825 - acc: 0.6222 - precision: 0.4696 - recall: 0.8964 - val_loss: 0.5232 - val_acc: 0.7755 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 307/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5755 - acc: 0.6511 - precision: 0.4843 - recall: 0.91

Epoch 341/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5943 - acc: 0.6267 - precision: 0.4729 - recall: 0.9128 - val_loss: 0.5140 - val_acc: 0.7755 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 342/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5791 - acc: 0.6400 - precision: 0.4649 - recall: 0.8982 - val_loss: 0.5176 - val_acc: 0.7755 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 343/500
450/450 [==============================] - 2s 5ms/step - loss: 0.5907 - acc: 0.6467 - precision: 0.4653 - recall: 0.9112 - val_loss: 0.5171 - val_acc: 0.7959 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 344/500
450/450 [==============================] - 2s 5ms/step - loss: 0.5877 - acc: 0.6489 - precision: 0.4789 - recall: 0.8708 - val_loss: 0.5227 - val_acc: 0.8163 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 345/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5812 - acc: 0.6289 - precision: 0.4783 - recall: 0.91

Epoch 379/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5801 - acc: 0.6378 - precision: 0.4840 - recall: 0.8985 - val_loss: 0.5268 - val_acc: 0.6327 - val_precision: 0.6000 - val_recall: 1.0000
Epoch 380/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5805 - acc: 0.6978 - precision: 0.4887 - recall: 0.8595 - val_loss: 0.5183 - val_acc: 0.6735 - val_precision: 0.6000 - val_recall: 1.0000
Epoch 381/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5831 - acc: 0.6378 - precision: 0.4722 - recall: 0.8680 - val_loss: 0.5161 - val_acc: 0.7143 - val_precision: 0.6000 - val_recall: 1.0000
Epoch 382/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5901 - acc: 0.6422 - precision: 0.4588 - recall: 0.8523 - val_loss: 0.5178 - val_acc: 0.6735 - val_precision: 0.6176 - val_recall: 1.0000
Epoch 383/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5769 - acc: 0.6556 - precision: 0.4812 - recall: 0.89

Epoch 417/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5875 - acc: 0.6467 - precision: 0.4534 - recall: 0.8488 - val_loss: 0.5071 - val_acc: 0.7755 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 418/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5673 - acc: 0.6511 - precision: 0.5037 - recall: 0.9073 - val_loss: 0.5069 - val_acc: 0.7755 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 419/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5883 - acc: 0.6489 - precision: 0.4696 - recall: 0.8863 - val_loss: 0.5066 - val_acc: 0.7959 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 420/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5838 - acc: 0.6356 - precision: 0.4802 - recall: 0.8999 - val_loss: 0.5067 - val_acc: 0.7755 - val_precision: 0.5676 - val_recall: 1.0000
Epoch 421/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5990 - acc: 0.6578 - precision: 0.4696 - recall: 0.87

Epoch 455/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5794 - acc: 0.6733 - precision: 0.4555 - recall: 0.9177 - val_loss: 0.5133 - val_acc: 0.7959 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 456/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5747 - acc: 0.6422 - precision: 0.4799 - recall: 0.9312 - val_loss: 0.5169 - val_acc: 0.7959 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 457/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5750 - acc: 0.6422 - precision: 0.4955 - recall: 0.9262 - val_loss: 0.5169 - val_acc: 0.7551 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 458/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5701 - acc: 0.6556 - precision: 0.4838 - recall: 0.9191 - val_loss: 0.5153 - val_acc: 0.7551 - val_precision: 0.5833 - val_recall: 1.0000
Epoch 459/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5860 - acc: 0.6200 - precision: 0.4787 - recall: 0.89

Epoch 493/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5842 - acc: 0.6244 - precision: 0.4726 - recall: 0.9033 - val_loss: 0.5400 - val_acc: 0.6327 - val_precision: 0.6364 - val_recall: 1.0000
Epoch 494/500
450/450 [==============================] - 1s 3ms/step - loss: 0.5743 - acc: 0.6511 - precision: 0.4678 - recall: 0.8624 - val_loss: 0.5359 - val_acc: 0.6327 - val_precision: 0.6364 - val_recall: 1.0000
Epoch 495/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5709 - acc: 0.6556 - precision: 0.4783 - recall: 0.9028 - val_loss: 0.5313 - val_acc: 0.6327 - val_precision: 0.6364 - val_recall: 1.0000
Epoch 496/500
450/450 [==============================] - 2s 3ms/step - loss: 0.5910 - acc: 0.6289 - precision: 0.4760 - recall: 0.8690 - val_loss: 0.5219 - val_acc: 0.6735 - val_precision: 0.6364 - val_recall: 1.0000
Epoch 497/500
450/450 [==============================] - 2s 4ms/step - loss: 0.5587 - acc: 0.6489 - precision: 0.5130 - recall: 0.93

In [3]:
# thresholds = [i/10 for i in range(11)]
# precision_at_diff_thresholds = []
# recall_at_diff_thresholds = []
# for threshold in thresholds:
#     print (threshold)
#     best_model_path, model, history = siamese.train_model(sentences_pair, is_similar, embedding_meta_data, model_save_directory='./', epochs = 200, threshold = threshold)
#     precision_at_diff_thresholds.append(history.history['precision'][-1])
#     recall_at_diff_thresholds.append(history.history['recall'][-1])

In [7]:
best_model_path = './checkpoints/lstm_%d_%d_%.2f_%.2f/lstm_%d_%d_%.2f_%.2f.h5' % (CONFIG.number_lstm_units, CONFIG.number_dense_units, CONFIG.rate_drop_lstm, CONFIG.rate_drop_dense, CONFIG.number_lstm_units, CONFIG.number_dense_units, CONFIG.rate_drop_lstm, CONFIG.rate_drop_dense)


In [ ]:
# best_model_path, model, history = siamese.update_model(best_model_path, sentences_pair, is_similar, embedding_meta_data, epochs = 50, threshold = 0.1)

In [8]:
def predictor(sentence):
    sent_test = []
    for i in range(len(sentences1 + sentences2)):
        sent_test.append(sentence)

    # print (sent_test)
    # print (len(sent_test))
    test_sentences_pair = [(x1, x2) for x1, x2 in zip(sent_test,sentences1 + sentences2)]
    # print (len(test_sentences_pair))
    # print (test_sentences_pair)
    test_data_x1, test_data_x2, leaks_test = create_test_data(tokenizer,test_sentences_pair,  siamese_config['MAX_SEQUENCE_LENGTH'])
    # print (test_data_x1[0:10])
    # print (test_data_x2[0:10])
    # print (leaks_test[0:10])
    preds = list(model.predict([test_data_x1, test_data_x2, leaks_test], verbose=0).ravel())
    # print (len(preds))
    results = [(x, y, z) for (x, y), z in zip(test_sentences_pair, preds)]
    results.sort(key=itemgetter(2), reverse=True)
    for i in range(5):
        print(results[i][1:])
        
        
# print (best_model_path,'\n')
# model = load_model(best_model_path, custom_objects = {'precision' : precision_threshold(0.3), 'recall':recall_threshold(0.3)})
sentence = 'how to be a great geologist'
predictor(sentence)        

('What should I do to be a great geologist?', 0.5764089)
('How can I be a good geologist?', 0.546425)
('How does Quora look to a moderator?', 0.541574)
("What's it like to be a firefighter?", 0.5317423)
('How accurately can a mental illness can be diagnosed?', 0.5229017)


In [59]:
sentence = 'how to avoid drugs'
predictor(sentence)

('How do I utilize free time to avoid depression?', 0.5506426)
('How to make friends ?', 0.542944)
('How can one learn to trust again?', 0.51589745)
('How do we avoid whey in Yogurt?', 0.51450825)
('How does Quora look to a moderator?', 0.51086336)


In [60]:
sentence = 'buy from amazon'
predictor(sentence)

('Should I buy tiago?', 0.49388272)
('How do I earn from Quora?', 0.43972158)
('What is CPAGrip.com?', 0.4222716)
('What is bestmytest.com?', 0.4222716)
('Do animals kiss?', 0.4150909)


In [34]:
sentence = 'what is the best way to start learning'
predictor(sentence)

('What is the best way to become a billionaire?', 0.5711422)
('What is the best way to get traffic on your website?', 0.57000434)
('What is the best way to start robotics? Which is the best development board that I can start working on it?', 0.56670696)
('What is the best phone to buy below 15k?', 0.55450886)
('What is the quickest way to increase Instagram followers?', 0.5535506)


In [13]:
sentence = 'share market invest'
predictor(sentence)

('What is the step by step guide to invest in share market?', 0.4954316)
('What is the step by step guide to invest in share market in india?', 0.4521498)
('What is CPAGrip.com?', 0.40070257)
('What is bestmytest.com?', 0.40070257)
('Do animals kiss?', 0.39355332)


In [14]:
sentence = 'dont ask questions'
predictor(sentence)

('What are the questions should not ask on Quora?', 0.47282192)
('What should I ask my crush?', 0.43335855)
('What is CPAGrip.com?', 0.4203115)
('What is bestmytest.com?', 0.4203115)
('Do animals kiss?', 0.41275564)


In [15]:
sentence = 'language'
predictor(sentence)

('Which is the best programming language?', 0.47780427)
('Which is the best programing language for tcs?', 0.4390646)
('What is CPAGrip.com?', 0.43452653)
('What is bestmytest.com?', 0.43452653)
('Do animals kiss?', 0.42676213)


In [16]:
sentence = 'best'
predictor(sentence)

('Which are the best engineering fields?', 0.50202715)
('What is the best travel website?', 0.4791104)
('What is the best fixed income fund?', 0.47903904)
('Which is the best programming language?', 0.4707394)
('Which is the best fixed income fund?', 0.47049996)


In [17]:
sentence = 'speed of '
predictor(sentence)

('How is the average speed of gas molecules determined?', 0.5096491)
('What is purpose of life?', 0.46092185)
('Who were the creators of trigonometry?', 0.45317978)
('How do you think of Chinese food?', 0.43683353)
('What are the types of immunity?', 0.4361958)


In [18]:
sentence = 'good to study'
predictor(sentence)

('What are good books to self study calculus?', 0.5916081)
('What are some tricks to study effectively?', 0.51542586)
('How to make friends ?', 0.45997742)
('How should I study', 0.4598097)
('What should I do to be a good Speaker?', 0.45300236)


In [19]:
sentence = 'difference'
predictor(sentence)

("What's the difference between between and among?", 0.47038653)
("What's the difference between love and pity?", 0.46999732)
("What's the difference between honest and sincere?", 0.46986407)
('What is the difference between love and pity?', 0.44565904)
('What is the difference between bay, gulf and straits?', 0.44563234)


In [61]:
sentence = 'meaning of'
predictor(sentence)

('What is the meaning of the future?', 0.55199736)
("What's are the meaning of life?", 0.547777)
('What the meaning of this all life?', 0.5373272)
('What is purpose of life?', 0.4606711)
('Who were the creators of trigonometry?', 0.45298803)


In [21]:
sentence = 'What are the pros and cons of a pet dog?'
predictor(sentence)

('What are the pros and cons of having a pet German Shepherd?', 0.5895676)
('What are the pros and cons of the Common Core Standards Initiative?', 0.5690705)
('What are the pros and cons of the German Shepherd dog?', 0.56597865)
('What are the disadvantages of listing a company in NSE?', 0.52503324)
('What are the benefits of listing a company in NSE?', 0.5249763)


In [22]:
sentence = 'pros and cons'
predictor(sentence)

('What are the pros and cons of the German Shepherd dog?', 0.5251115)
('What are the pros and cons of the Common Core Standards Initiative?', 0.48747477)
('What are the pros and cons of having a pet German Shepherd?', 0.4348281)
('What exactly is the "Common Core Initiative/Standards" and what are the pros and cons?', 0.4329614)
('What is CPAGrip.com?', 0.40378097)


In [23]:
sentence = 'How can I stop being afraid of working?'
predictor(sentence)

('How can I stop being afraid of working?', 0.5554533)
('How can I stop being addicted to love?', 0.5550023)
('How do you stop being afraid of everything?', 0.5547821)
('How can I stop being so possessive?', 0.5492381)
('How can I maintain my peace of mind?', 0.53376925)


In [24]:
sentence = 'What are some examples of sentences using the word "hysteria"?'
predictor(sentence)

('What are some examples of sentences using the word "hysteria"?', 0.5497296)
('What are some of the best rap songs?', 0.5424606)
('What are some of the products made from crude oil?', 0.5420189)
('What are some of the major influences of abstract expressionism?', 0.54094857)
('What are some of the best YouTube channels for learning Git?', 0.5309045)


In [25]:
sentence = 'What is journalism?'
predictor(sentence)

('What is journalism for you?', 0.5868764)
('What is the cheapest toothpaste?', 0.5401307)
('What is a Yantra & Mantra?', 0.5393327)
('What is my puk code?', 0.53770065)
('What is your bucket list?', 0.53614205)


In [26]:
sentence = 'Operation executive salary in Infosys?'
predictor(sentence)

('Operation executive salary in Infosys?', 0.5277201)
('Will Modi win in 2019?', 0.43058425)
('What is in bone marrow?', 0.41077903)
('Which course is better in NICMAR?', 0.39602327)
('How can I get entry in MIT?', 0.37966445)


In [27]:
sentence = 'If space is expanding, where does the new space come from?'
predictor(sentence)

('If space is expanding, where does the new space come from?', 0.5481141)
('How bad is the new book by J.K Rowling?', 0.41789234)
('What is the web application framework?', 0.3830253)
('What is the strongest Kevlar cord?', 0.38292155)
('How is The Canterbury Tales a satire?', 0.3736614)


In [28]:
sentence = 'What is the best recipe for chicken pizza?'
predictor(sentence)

('What is the best reference book for physics class 11th?', 0.5546011)
('What is the best recipe for chicken pizza?', 0.55419713)
('What is the best diet for a growing decathlete?', 0.55255127)
('What is the best university in Germany for an MS?', 0.54940265)
('What is the best forum for graphic designers?', 0.54641575)


In [35]:
sentence = 'What is the best forum for graphic designers?'
predictor(sentence)

('What is the best recipe for chicken pizza?', 0.56831)
('What is the best reference book for physics class 11th?', 0.5660164)
('What is the best diet for a growing decathlete?', 0.56512356)
('What is the best university in Germany for an MS?', 0.56161845)
('What is the best forum for graphic designers?', 0.5531717)


In [30]:
sentence = 'How bad is the new book by J.K Rowling?'
predictor(sentence)

('How bad is the new book by J.K Rowling?', 0.553813)
("How is the new Harry Potter book 'Harry Potter and the Cursed Child'?", 0.54201293)
('How is The Canterbury Tales a satire?', 0.49521947)
('What is the best book ever made?', 0.47748813)
('How is the average speed of gas molecules determined?', 0.44735038)


In [31]:
sentence = 'How is The Canterbury Tales a satire?'
predictor(sentence)

('How is The Canterbury Tales a satire?', 0.5524609)
('What is the temperament of a Bullmastiff/Husky mix?', 0.5253306)
('What is the temperament of a Corgi-Husky mix?', 0.5253306)
('How does a fetus exhale in the womb?', 0.5082909)
('What is the cheapest toothpaste?', 0.48646894)


In [44]:
sentence = 'What universities does Industries recruit new grads from? What majors are they looking for?'
predictor(sentence)

('What universities does Sigma Designs recruit new grads from? What majors are they looking for?', 0.5517547)
('What universities does B&G Foods recruit new grads from? What majors are they looking for?', 0.55132717)
('What universities does Sigma-Aldrich recruit new grads from? What majors are they looking for?', 0.54947156)
('What universities does Rexnord recruit new grads from? What majors are they looking for?', 0.5494174)
('What universities does Chart Industries recruit new grads from? What majors are they looking for?', 0.54571015)


In [47]:
sentence = 'What is the best way to live'
predictor(sentence)

('What is the best way to get traffic on your website?', 0.6023152)
('What is the way to watch Comedy Nights with Kapil live on the sets?', 0.6002866)
('What is the best way to become a billionaire?', 0.5891419)
('What is the best phone to buy below 15k?', 0.56713414)
('What is the quickest way to increase Instagram followers?', 0.5662622)


In [58]:
sentence = 'What is a least natural number?'
predictor(sentence)

('What is a least natural number?', 0.5524322)
('What is a cover story?', 0.52824557)
('What is a narcissistic personality disorder?', 0.52817214)
('What is the temperament of a Bullmastiff/Husky mix?', 0.52756727)
('What is the temperament of a Corgi-Husky mix?', 0.52756727)


In [57]:
sentence = 'What is a natural number?'
predictor(sentence)

('What is a least natural number?', 0.5747281)
('What is a cover story?', 0.5419528)
('What is a narcissistic personality disorder?', 0.5418925)
('What is the temperament of a Bullmastiff/Husky mix?', 0.54161316)
('What is the temperament of a Corgi-Husky mix?', 0.54161316)


In [53]:
sentence = 'Can I make 100,000 a month?'
predictor(sentence)

('Can I make 50,000 a month by day trading?', 0.6168979)
('Can I make 30,000 a month by day trading?', 0.61687696)
('How can I be a good geologist?', 0.54656726)
('How can I become a billionaire?', 0.5465086)
('How can I become a good speaker?', 0.54596263)


In [49]:
sentence = "Do you apply for programs like RSI when you're a rising senior?"
predictor(sentence)

("Do you apply for programs like RSI when you're a rising senior?", 0.5499433)
('How do you get a book published?', 0.4291916)
('How do you register a .an domain?', 0.41486493)
('How do you keep motivated when you learn a new language?', 0.41460964)
('When do you use "&" instead of "and"?', 0.4025544)


In [50]:
sentence = "Do you apply for car loans?"
predictor(sentence)

("Do you apply for programs like RSI when you're a rising senior?", 0.5149193)
('Do you regret your divorce?', 0.5006508)
('Do you need friends?', 0.4987615)
('How do we prepare for UPSC?', 0.49759206)
('What is journalism for you?', 0.49394774)


In [32]:
# train_data_x1, train_data_x2, train_labels, leaks_train, val_data_x1, val_data_x2, val_labels, leaks_val = create_train_dev_set(tokenizer, sentences_pair,
#                                                                                is_similar, CONFIG.max_sequence_length,
#                                                                                CONFIG.validation_split_ratio)
# print (train_data_x1.shape)
# print (train_data_x1[:10])
# print (train_data_x2.shape)
# print (train_data_x2[:10])
# print (val_data_x1.shape)
# print (val_data_x2.shape)
# print (leaks_train.shape)
# print (leaks_val.shape)

(450, 12)
[[   2  673 1391    1 1392  674 2483    0    0    0    0    0]
 [   2   19    1  424  328 1999   22    1 1005 2000 2001  210]
 [   2   11    1  134  983  784    8   67    0    0    0    0]
 [   2    3    8  864 2620    0    0    0    0    0    0    0]
 [   1  121    6  824    8    1 1187   15    9  826 1619  827]
 [   4    9   40  320 1860    8    0    0    0    0    0    0]
 [ 642  398   10 1075    4    3    1  399  109   45    0    0]
 [  33   13    5  270   16  574  575    0    0    0    0    0]
 [   4    9    5   55  211    0    0    0    0    0    0    0]
 [1828  959  175   44  176   29    2  177   11   50  147   14]]
(450, 12)
[[   2  673   13 1126    1  413  674 2483    0    0    0    0]
 [   4    9   17   60    6 2924 2925   72   58    8    6    0]
 [  24   11    1  134 2800    8  364  983 2801    8   67   12]
 [   2   19  864 2620 2621   39    0    0    0    0    0    0]
 [   8    6  824    8    1 1187   15    9  826   12  827    0]
 [   3  200 2783    6 2784   10   

In [33]:
# test_sentence_pairs = [('What can make Physics easy to learn?','How can you make chemistry easy to learn?'),('What can make Physics easy to learn?','How can you make physics easy to learn?'),('What can make Physics easy to learn?','I am a boy.')]
# #                        ,('How many times a day do a clocks hands overlap?','What does it mean that every time I look at the clock the numbers are the same?')]

# test_data_x1, test_data_x2, leaks_test = create_test_data(tokenizer,test_sentence_pairs,  siamese_config['MAX_SEQUENCE_LENGTH'])
# # print (test_data_x1.shape)
# # print (test_data_x2.shape)

# preds = list(model.predict([test_data_x1, test_data_x2, leaks_test], verbose=0).ravel())
# results = [(x, y, z) for (x, y), z in zip(test_sentence_pairs, preds)]
# results.sort(key=itemgetter(2), reverse=True)
# print(results)